version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: integration
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_DB: mongodb://username:password@localhost:27017/mydatabase
      # username и password — учетные данные для подключения.

volumes:
  mongo-data:
